### ISSUE TITLE
tag v0.1.5

### ISSUE THREAD

**Issue by keisuk-t** [iij/p2pubapi#28]
v0.1.4以降にいくつかアップデートされていますが、タグが打たれていません。よろしければ、対応をおねがいします。

go get -uするとmasterよりも最新のtagが優先されるため、v0.1.4が採用されてしまい少しばかり面倒です。主にlogrusのために。

**Comment by wtnb75** [comment]
お待たせしました
https://github.com/iij/p2pubapi/releases/tag/v0.1.5

**Comment by keisuk-t** [comment]
ありがとうございます！
